[09-May-24 10:06:10 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 10:06:10 - INFO] - bot - Bot stopped.
[09-May-24 10:06:19 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 10:06:19 - INFO] - bot - Lets roll
[09-May-24 10:12:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 10:12:40 - INFO] - bot - Bot stopped.
[09-May-24 10:12:49 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 10:12:49 - INFO] - bot - Lets roll
[09-May-24 10:14:12 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 10:14:12 - INFO] - bot - Bot stopped.
[09-May-24 10:14:20 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 10:14:20 - INFO] - bot - Lets roll
[09-May-24 10:26:54 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[09-May-24 10:29:09 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 10:29:09 - INFO] - bot - Bot stopped.
[09-May-24 10:29:19 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 10:29:19 - INFO] - bot - Lets roll
[09-May-24 10:32:42 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 10:32:42 - INFO] - bot - Bot stopped.
[09-May-24 10:32:51 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 10:32:51 - INFO] - bot - Lets roll
[09-May-24 10:43:33 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 10:43:33 - INFO] - bot - Bot stopped.
[09-May-24 10:43:45 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 10:43:45 - INFO] - bot - Lets roll
[09-May-24 10:44:00 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 10:44:00 - INFO] - bot - Bot stopped.
[09-May-24 10:44:08 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 10:44:08 - INFO] - bot - Lets roll
[09-May-24 10:44:41 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 10:44:41 - INFO] - bot - Bot stopped.
[09-May-24 10:44:50 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 10:44:50 - INFO] - bot - Lets roll
[09-May-24 10:46:10 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 10:46:10 - INFO] - bot - Bot stopped.
[09-May-24 10:46:19 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 10:46:19 - INFO] - bot - Lets roll
[09-May-24 10:47:30 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 10:47:30 - INFO] - bot - Bot stopped.
[09-May-24 10:47:38 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 10:47:38 - INFO] - bot - Lets roll
[09-May-24 10:49:48 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 10:49:48 - INFO] - bot - Bot stopped.
[09-May-24 10:49:56 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 10:49:56 - INFO] - bot - Lets roll
[09-May-24 10:51:21 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 10:51:21 - INFO] - bot - Bot stopped.
[09-May-24 10:51:29 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 10:51:29 - INFO] - bot - Lets roll
[09-May-24 10:52:05 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 10:52:05 - INFO] - bot - Bot stopped.
[09-May-24 10:52:14 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 10:52:14 - INFO] - bot - Lets roll
[09-May-24 10:53:53 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 10:53:53 - INFO] - bot - Bot stopped.
[09-May-24 10:54:01 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 10:54:01 - INFO] - bot - Lets roll
[09-May-24 10:54:42 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 10:54:42 - INFO] - bot - Bot stopped.
[09-May-24 10:54:50 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 10:54:50 - INFO] - bot - Lets roll
[09-May-24 11:31:19 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 11:31:19 - INFO] - bot - Bot stopped.
[09-May-24 11:31:28 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 11:31:28 - INFO] - bot - Lets roll
[09-May-24 11:38:39 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 11:38:39 - INFO] - bot - Bot stopped.
[09-May-24 11:38:48 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 11:38:48 - INFO] - bot - Lets roll
[09-May-24 11:41:27 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 11:41:27 - INFO] - bot - Bot stopped.
[09-May-24 11:41:36 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 11:41:36 - INFO] - bot - Lets roll
[09-May-24 11:42:20 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 11:42:20 - INFO] - bot - Bot stopped.
[09-May-24 11:42:28 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 11:42:28 - INFO] - bot - Lets roll
[09-May-24 11:46:05 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 11:46:05 - INFO] - bot - Bot stopped.
[09-May-24 11:46:14 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 11:46:14 - INFO] - bot - Lets roll
[09-May-24 11:51:08 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 11:51:08 - INFO] - bot - Bot stopped.
[09-May-24 11:51:20 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 11:51:20 - INFO] - bot - Lets roll
[09-May-24 11:55:10 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 11:55:10 - INFO] - bot - Bot stopped.
[09-May-24 11:55:19 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 11:55:19 - INFO] - bot - Lets roll
[09-May-24 11:55:31 - ERROR] - pyrogram.dispatcher - cannot access local variable 'message' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\callback_query_handler.py", line 58, in callback_handler
    return await start_command(client, message)
                                       ^^^^^^^
UnboundLocalError: cannot access local variable 'message' where it is not associated with a value
[09-May-24 11:56:01 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 11:56:01 - INFO] - bot - Bot stopped.
[09-May-24 11:56:09 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 11:56:09 - INFO] - bot - Lets roll
[09-May-24 11:57:06 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 11:57:06 - INFO] - bot - Bot stopped.
[09-May-24 11:57:14 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 11:57:14 - INFO] - bot - Lets roll
[09-May-24 11:57:28 - ERROR] - pyrogram.dispatcher - 'ascii' codec can't encode character '\u25cb' in position 22: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\callback_query_handler.py", line 58, in callback_handler
    return await start_command(client, message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\start_command.py", line 87, in start_command
    ids = await extract_ids(client, decoded_message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\helper_func.py", line 83, in extract_ids
    string = await decode(base64_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\helper_func.py", line 161, in decode
    base64_bytes = (base64_string + "=" * (-len(base64_string) % 4)).encode("ascii")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\u25cb' in position 22: ordinal not in range(128)
[09-May-24 11:58:23 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 11:58:23 - INFO] - bot - Bot stopped.
[09-May-24 11:58:31 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 11:58:31 - INFO] - bot - Lets roll
[09-May-24 12:02:43 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 12:02:43 - INFO] - bot - Bot stopped.
[09-May-24 12:02:51 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 12:02:51 - INFO] - bot - Lets roll
[09-May-24 12:03:24 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 12:03:24 - INFO] - bot - Bot stopped.
[09-May-24 12:03:32 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 12:03:32 - INFO] - bot - Lets roll
[09-May-24 12:08:42 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 12:08:42 - INFO] - bot - Bot stopped.
[09-May-24 12:08:50 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 12:08:50 - INFO] - bot - Lets roll
[09-May-24 12:10:29 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 12:10:29 - INFO] - bot - Bot stopped.
[09-May-24 12:10:38 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 12:10:38 - INFO] - bot - Lets roll
[09-May-24 12:16:08 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 12:16:08 - INFO] - bot - Bot stopped.
[09-May-24 12:16:16 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 12:16:16 - INFO] - bot - Lets roll
[09-May-24 12:19:05 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 12:19:05 - INFO] - bot - Bot stopped.
[09-May-24 12:19:13 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 12:19:13 - INFO] - bot - Lets roll
[09-May-24 12:25:09 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 12:25:09 - INFO] - bot - Bot stopped.
[09-May-24 12:30:35 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 12:30:35 - INFO] - bot - Lets roll
[09-May-24 12:32:10 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 12:32:10 - INFO] - bot - Bot stopped.
[09-May-24 12:32:23 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 12:32:23 - INFO] - bot - Lets roll
[09-May-24 12:32:44 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 12:32:44 - INFO] - bot - Bot stopped.
[09-May-24 12:32:55 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 12:32:55 - INFO] - bot - Lets roll
[09-May-24 12:35:21 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 12:35:21 - INFO] - bot - Bot stopped.
[09-May-24 12:35:36 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 12:35:36 - INFO] - bot - Lets roll
[09-May-24 12:37:12 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 12:37:12 - INFO] - bot - Bot stopped.
[09-May-24 12:37:25 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 12:37:25 - INFO] - bot - Lets roll
[09-May-24 12:39:02 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 12:39:02 - INFO] - bot - Bot stopped.
[09-May-24 12:39:16 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 12:39:16 - INFO] - bot - Lets roll
[09-May-24 12:40:04 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 12:40:04 - INFO] - bot - Bot stopped.
[09-May-24 12:40:16 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 12:40:16 - INFO] - bot - Lets roll
[09-May-24 12:41:10 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 12:41:10 - INFO] - bot - Bot stopped.
[09-May-24 12:41:24 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 12:41:24 - INFO] - bot - Lets roll
[09-May-24 12:42:06 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 12:42:06 - INFO] - bot - Bot stopped.
[09-May-24 12:42:19 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 12:42:19 - INFO] - bot - Lets roll
[09-May-24 13:06:42 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[09-May-24 13:06:53 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[09-May-24 13:07:04 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[09-May-24 13:07:05 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:07:15 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[09-May-24 13:07:26 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[09-May-24 13:07:27 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:28 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:07:28 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:29 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:30 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:31 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:07:31 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:32 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:33 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:34 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:07:34 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:35 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:36 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:37 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:07:37 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:39 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:40 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:41 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:07:41 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:42 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:43 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:44 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:07:44 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:45 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:46 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:47 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:07:47 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:48 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:49 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:50 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:07:50 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:51 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:52 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:53 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:07:53 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:54 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:55 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:56 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:07:56 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:57 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:58 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:07:59 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:07:59 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:00 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:01 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:02 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:08:02 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:03 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:04 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:05 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:08:05 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:06 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:07 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:08 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:08:08 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:09 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:10 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:11 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:08:11 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:12 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:13 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:14 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:08:14 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:15 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:16 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:17 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:08:17 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:18 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:19 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:20 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:08:20 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:21 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:22 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:23 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:08:23 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:24 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:25 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:26 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:08:26 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:27 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:28 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:29 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:08:29 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:30 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:31 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:32 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:08:32 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:33 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:34 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:35 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:08:35 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:36 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:37 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:38 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:08:38 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:39 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:40 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:41 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:08:41 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:42 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:43 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:44 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[09-May-24 13:08:44 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:08:45 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[09-May-24 13:18:41 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 13:18:41 - INFO] - bot - Bot stopped.
[09-May-24 13:18:49 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 13:18:49 - INFO] - bot - Lets roll
[09-May-24 13:18:58 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 13:18:58 - INFO] - bot - Bot stopped.
[09-May-24 22:44:18 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 22:44:18 - INFO] - bot - Lets roll
[09-May-24 22:45:11 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 22:45:11 - INFO] - bot - Bot stopped.
[09-May-24 22:45:20 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 22:45:20 - INFO] - bot - Lets roll
[09-May-24 22:46:13 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 22:46:13 - INFO] - bot - Bot stopped.
[09-May-24 22:46:25 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 22:46:25 - INFO] - bot - Lets roll
[09-May-24 22:47:05 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 22:47:05 - INFO] - bot - Bot stopped.
[09-May-24 22:47:13 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 22:47:13 - INFO] - bot - Lets roll
[09-May-24 22:47:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 22:47:40 - INFO] - bot - Bot stopped.
[09-May-24 22:47:50 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 22:47:50 - INFO] - bot - Lets roll
[09-May-24 22:51:49 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 22:51:49 - INFO] - bot - Bot stopped.
[09-May-24 22:51:57 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 22:51:57 - INFO] - bot - Lets roll
[09-May-24 22:52:15 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 22:52:15 - INFO] - bot - Bot stopped.
[09-May-24 22:52:25 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 22:52:25 - INFO] - bot - Lets roll
[09-May-24 22:52:29 - ERROR] - pyrogram.dispatcher - 'Searching' object has no attribute 'get_all_seachings'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\on_message.py", line 42, in handle_message
    return await command_call(client, message, command_ext["name"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\managers\command\methods.py", line 15, in command_call
    await comm["method"](bot, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\statistics_command.py", line 17, in statistics_command
    queries = Searching().get_all_seachings()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Searching' object has no attribute 'get_all_seachings'
[09-May-24 22:53:24 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 22:53:24 - INFO] - bot - Bot stopped.
[09-May-24 22:53:32 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 22:53:32 - INFO] - bot - Lets roll
[09-May-24 23:01:01 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:01:01 - INFO] - bot - Bot stopped.
[09-May-24 23:01:09 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:01:09 - INFO] - bot - Lets roll
[09-May-24 23:02:59 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:02:59 - INFO] - bot - Bot stopped.
[09-May-24 23:03:08 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:03:08 - INFO] - bot - Lets roll
[09-May-24 23:03:11 - ERROR] - pyrogram.dispatcher - tuple indices must be integers or slices, not str
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\on_message.py", line 42, in handle_message
    return await command_call(client, message, command_ext["name"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\managers\command\methods.py", line 15, in command_call
    await comm["method"](bot, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\statistics_command.py", line 26, in statistics_command
    total_downloads = sum(query["downloads"] for query in queries)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\statistics_command.py", line 26, in <genexpr>
    total_downloads = sum(query["downloads"] for query in queries)
                          ~~~~~^^^^^^^^^^^^^
TypeError: tuple indices must be integers or slices, not str
[09-May-24 23:03:28 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:03:28 - INFO] - bot - Bot stopped.
[09-May-24 23:03:36 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:03:36 - INFO] - bot - Lets roll
[09-May-24 23:03:40 - ERROR] - pyrogram.dispatcher - tuple indices must be integers or slices, not str
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\on_message.py", line 42, in handle_message
    return await command_call(client, message, command_ext["name"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\managers\command\methods.py", line 15, in command_call
    await comm["method"](bot, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\statistics_command.py", line 26, in statistics_command
    total_downloads = sum(query["downloads"] for query in queries)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\statistics_command.py", line 26, in <genexpr>
    total_downloads = sum(query["downloads"] for query in queries)
                          ~~~~~^^^^^^^^^^^^^
TypeError: tuple indices must be integers or slices, not str
[09-May-24 23:08:34 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:08:34 - INFO] - bot - Bot stopped.
[09-May-24 23:08:42 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:08:42 - INFO] - bot - Lets roll
[09-May-24 23:08:51 - ERROR] - pyrogram.dispatcher - sequence item 0: expected str instance, int found
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\on_message.py", line 42, in handle_message
    return await command_call(client, message, command_ext["name"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\managers\command\methods.py", line 15, in command_call
    await comm["method"](bot, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\statistics_command.py", line 24, in statistics_command
    _common = _searchings.most_common_searched_word()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\models\searchings.py", line 70, in most_common_searched_word
    combined_text = ' '.join(searched_for_texts)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, int found
[09-May-24 23:09:49 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:09:49 - INFO] - bot - Bot stopped.
[09-May-24 23:09:58 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:09:58 - INFO] - bot - Lets roll
[09-May-24 23:10:00 - ERROR] - pyrogram.dispatcher - sequence item 0: expected str instance, int found
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\on_message.py", line 42, in handle_message
    return await command_call(client, message, command_ext["name"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\managers\command\methods.py", line 15, in command_call
    await comm["method"](bot, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\statistics_command.py", line 24, in statistics_command
    _common = _searchings.most_common_searched_word()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\models\searchings.py", line 71, in most_common_searched_word
    combined_text = ' '.join(searched_for_texts)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, int found
[09-May-24 23:10:09 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:10:09 - INFO] - bot - Bot stopped.
[09-May-24 23:10:18 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:10:18 - INFO] - bot - Lets roll
[09-May-24 23:10:30 - ERROR] - pyrogram.dispatcher - 'Message' object has no attribute 'message_id'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\on_message.py", line 42, in handle_message
    return await command_call(client, message, command_ext["name"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\managers\command\methods.py", line 15, in command_call
    await comm["method"](bot, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\statistics_command.py", line 38, in statistics_command
    msg = await message.reply(stats_text, reply_to_message_id=message.message_id)
                                                              ^^^^^^^^^^^^^^^^^^
AttributeError: 'Message' object has no attribute 'message_id'
[09-May-24 23:11:16 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:11:16 - INFO] - bot - Bot stopped.
[09-May-24 23:11:25 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:11:25 - INFO] - bot - Lets roll
[09-May-24 23:14:00 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:14:00 - INFO] - bot - Bot stopped.
[09-May-24 23:14:09 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:14:09 - INFO] - bot - Lets roll
[09-May-24 23:14:11 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:14:11 - INFO] - bot - Bot stopped.
[09-May-24 23:14:45 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:14:45 - INFO] - bot - Lets roll
[09-May-24 23:15:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:15:40 - INFO] - bot - Bot stopped.
[09-May-24 23:15:49 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:15:49 - INFO] - bot - Lets roll
[09-May-24 23:16:51 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:16:51 - INFO] - bot - Bot stopped.
[09-May-24 23:17:00 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:17:00 - INFO] - bot - Lets roll
[09-May-24 23:19:36 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:19:36 - INFO] - bot - Bot stopped.
[09-May-24 23:19:44 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:19:44 - INFO] - bot - Lets roll
[09-May-24 23:20:04 - ERROR] - pyrogram.dispatcher - Invalid parse mode "HTML"
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\on_message.py", line 42, in handle_message
    return await command_call(client, message, command_ext["name"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\managers\command\methods.py", line 15, in command_call
    await comm["method"](bot, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\statistics_command.py", line 40, in statistics_command
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\messages_and_media\message.py", line 970, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\messages\send_message.py", line 124, in send_message
    message, entities = (await utils.parse_text_entities(self, text, parse_mode, entities)).values()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\utils.py", line 354, in parse_text_entities
    text, entities = (await client.parser.parse(text, parse_mode)).values()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\parser\parser.py", line 54, in parse
    raise ValueError(f'Invalid parse mode "{mode}"')
ValueError: Invalid parse mode "HTML"
[09-May-24 23:20:14 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:20:14 - INFO] - bot - Bot stopped.
[09-May-24 23:20:27 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:20:27 - INFO] - bot - Lets roll
[09-May-24 23:40:03 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:40:03 - INFO] - bot - Bot stopped.
[09-May-24 23:40:33 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:40:33 - INFO] - bot - Lets roll
[09-May-24 23:41:52 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:41:52 - INFO] - bot - Bot stopped.
[09-May-24 23:42:01 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:42:01 - INFO] - bot - Lets roll
[09-May-24 23:43:06 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:43:06 - INFO] - bot - Bot stopped.
[09-May-24 23:43:18 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:43:18 - INFO] - bot - Lets roll
[09-May-24 23:43:27 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:43:27 - INFO] - bot - Bot stopped.
[09-May-24 23:43:37 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:43:37 - INFO] - bot - Lets roll
[09-May-24 23:44:53 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:44:53 - INFO] - bot - Bot stopped.
[09-May-24 23:45:02 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:45:02 - INFO] - bot - Lets roll
[09-May-24 23:45:29 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:45:29 - INFO] - bot - Bot stopped.
[09-May-24 23:45:38 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:45:38 - INFO] - bot - Lets roll
[09-May-24 23:46:03 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:46:03 - INFO] - bot - Bot stopped.
[09-May-24 23:46:12 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:46:12 - INFO] - bot - Lets roll
[09-May-24 23:48:18 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:48:18 - INFO] - bot - Bot stopped.
[09-May-24 23:48:26 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:48:26 - INFO] - bot - Lets roll
[09-May-24 23:49:04 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:49:04 - INFO] - bot - Bot stopped.
[09-May-24 23:49:13 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:49:13 - INFO] - bot - Lets roll
[09-May-24 23:49:38 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:49:38 - INFO] - bot - Bot stopped.
[09-May-24 23:49:48 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:49:48 - INFO] - bot - Lets roll
[09-May-24 23:50:13 - INFO] - root - Stop signal received (SIGINT). Exiting...
[09-May-24 23:50:13 - INFO] - bot - Bot stopped.
[09-May-24 23:50:23 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[09-May-24 23:50:23 - INFO] - bot - Lets roll
[10-May-24 00:33:07 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 00:33:07 - INFO] - bot - Bot stopped.
[10-May-24 00:44:44 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 00:44:44 - INFO] - bot - Lets roll
[10-May-24 01:01:48 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:01:48 - INFO] - bot - Bot stopped.
[10-May-24 01:02:00 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:02:00 - INFO] - bot - Lets roll
[10-May-24 01:18:45 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:18:46 - INFO] - bot - Bot stopped.
[10-May-24 01:19:17 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:19:17 - INFO] - bot - Lets roll
[10-May-24 01:19:18 - ERROR] - pyrogram.dispatcher - object str can't be used in 'await' expression
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\on_message.py", line 51, in handle_message
    await check_link_command(client, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\check_link_command.py", line 17, in check_link_command
    type_link = await link_type(hasUrl)
                ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object str can't be used in 'await' expression
[10-May-24 01:19:36 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:19:36 - INFO] - bot - Bot stopped.
[10-May-24 01:19:48 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:19:48 - INFO] - bot - Lets roll
[10-May-24 01:25:11 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:25:11 - INFO] - bot - Bot stopped.
[10-May-24 01:25:21 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:25:21 - INFO] - bot - Lets roll
[10-May-24 01:25:29 - ERROR] - pyrogram.dispatcher - FacebookVideoDownloader.download() missing 1 required positional argument: 'url'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\on_message.py", line 51, in handle_message
    await check_link_command(client, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\check_link_command.py", line 24, in check_link_command
    result = facebook.download()
             ^^^^^^^^^^^^^^^^^^^
TypeError: FacebookVideoDownloader.download() missing 1 required positional argument: 'url'
[10-May-24 01:25:49 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:25:49 - INFO] - bot - Bot stopped.
[10-May-24 01:25:58 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:25:58 - INFO] - bot - Lets roll
[10-May-24 01:26:03 - ERROR] - pyrogram.dispatcher - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\on_message.py", line 51, in handle_message
    await check_link_command(client, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\check_link_command.py", line 25, in check_link_command
    if result["success"]:
       ~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[10-May-24 01:26:24 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:26:24 - INFO] - bot - Bot stopped.
[10-May-24 01:26:32 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:26:32 - INFO] - bot - Lets roll
[10-May-24 01:26:40 - ERROR] - pyrogram.dispatcher - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\on_message.py", line 51, in handle_message
    await check_link_command(client, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\check_link_command.py", line 26, in check_link_command
    if result["success"]:
       ~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[10-May-24 01:28:07 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:28:07 - INFO] - bot - Bot stopped.
[10-May-24 01:28:16 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:28:16 - INFO] - bot - Lets roll
[10-May-24 01:33:34 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:33:34 - INFO] - bot - Bot stopped.
[10-May-24 01:33:42 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:33:42 - INFO] - bot - Lets roll
[10-May-24 01:33:56 - ERROR] - pyrogram.dispatcher - CallbackDataManager.generate_callback_data() missing 1 required positional argument: 'data'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\on_message.py", line 51, in handle_message
    await check_link_command(client, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\check_link_command.py", line 33, in check_link_command
    callable_mdata = callable_m.generate_callback_data(callable_mdata)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CallbackDataManager.generate_callback_data() missing 1 required positional argument: 'data'
[10-May-24 01:34:26 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:34:26 - INFO] - bot - Bot stopped.
[10-May-24 01:34:35 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:34:35 - INFO] - bot - Lets roll
[10-May-24 01:37:00 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:37:00 - INFO] - bot - Bot stopped.
[10-May-24 01:37:14 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:37:14 - INFO] - bot - Lets roll
[10-May-24 01:38:07 - ERROR] - pyrogram.dispatcher - 'list' object has no attribute 'write'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\on_message.py", line 51, in handle_message
    return await check_link_command(client, message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\check_link_command.py", line 50, in check_link_command
    await message.reply_text(msg, reply_markup=buttons)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\messages_and_media\message.py", line 970, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\messages\send_message.py", line 134, in send_message
    reply_markup=await reply_markup.write(self) if reply_markup else None,
                       ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'write'
[10-May-24 01:41:17 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:41:17 - INFO] - bot - Bot stopped.
[10-May-24 01:41:27 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:41:27 - INFO] - bot - Lets roll
[10-May-24 01:43:42 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:43:42 - INFO] - bot - Bot stopped.
[10-May-24 01:43:54 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:43:54 - INFO] - bot - Lets roll
[10-May-24 01:46:10 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:46:10 - INFO] - bot - Bot stopped.
[10-May-24 01:46:18 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:46:18 - INFO] - bot - Lets roll
[10-May-24 01:47:36 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:47:36 - INFO] - bot - Bot stopped.
[10-May-24 01:47:44 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:47:44 - INFO] - bot - Lets roll
[10-May-24 01:48:23 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:48:23 - INFO] - bot - Bot stopped.
[10-May-24 01:48:31 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:48:31 - INFO] - bot - Lets roll
[10-May-24 01:50:20 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:50:20 - INFO] - bot - Lets roll
[10-May-24 01:52:37 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:52:37 - INFO] - bot - Bot stopped.
[10-May-24 01:52:46 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:52:46 - INFO] - bot - Lets roll
[10-May-24 01:53:49 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:53:49 - INFO] - bot - Bot stopped.
[10-May-24 01:53:58 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:53:58 - INFO] - bot - Lets roll
[10-May-24 01:58:47 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 01:58:47 - INFO] - bot - Bot stopped.
[10-May-24 01:58:56 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 01:58:56 - INFO] - bot - Lets roll
[10-May-24 02:00:29 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 02:00:29 - INFO] - bot - Bot stopped.
[10-May-24 02:00:38 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 02:00:38 - INFO] - bot - Lets roll
[10-May-24 02:02:31 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 02:02:31 - INFO] - bot - Bot stopped.
[10-May-24 02:02:39 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 02:02:39 - INFO] - bot - Lets roll
[10-May-24 02:09:50 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 02:09:50 - INFO] - bot - Bot stopped.
[10-May-24 02:13:16 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 02:13:16 - INFO] - bot - Lets roll
[10-May-24 02:16:04 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 02:16:04 - INFO] - bot - Bot stopped.
[10-May-24 02:16:16 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 02:16:16 - INFO] - bot - Lets roll
[10-May-24 02:21:04 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 02:21:04 - INFO] - bot - Bot stopped.
[10-May-24 02:21:13 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 02:21:13 - INFO] - bot - Lets roll
[10-May-24 02:21:49 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 02:21:49 - INFO] - bot - Bot stopped.
[10-May-24 02:21:57 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 02:21:57 - INFO] - bot - Lets roll
[10-May-24 02:22:18 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 02:22:18 - INFO] - bot - Bot stopped.
[10-May-24 02:22:27 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 02:22:27 - INFO] - bot - Lets roll
[10-May-24 07:45:34 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 07:45:34 - INFO] - bot - Bot stopped.
[10-May-24 07:45:43 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 07:45:43 - INFO] - bot - Lets roll
[10-May-24 07:50:01 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 07:50:01 - INFO] - bot - Bot stopped.
[10-May-24 07:50:10 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 07:50:10 - INFO] - bot - Lets roll
[10-May-24 07:50:19 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 07:50:19 - INFO] - bot - Bot stopped.
[10-May-24 07:50:27 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 07:50:27 - INFO] - bot - Lets roll
[10-May-24 07:55:50 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 07:55:50 - INFO] - bot - Bot stopped.
[10-May-24 07:55:58 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 07:55:58 - INFO] - bot - Lets roll
[10-May-24 07:56:12 - ERROR] - pyrogram.dispatcher - Telegram says: [400 BUTTON_DATA_INVALID] - The button callback data is invalid or too large (caused by "messages.EditMessage")
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\on_message.py", line 47, in handle_message
    return await check_link_command(client, message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\check_link_command.py", line 35, in check_link_command
    return await reply_text.edit_text(msg, reply_markup=keyboard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\messages_and_media\message.py", line 2803, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\messages\edit_message_text.py", line 82, in edit_message_text
    r = await self.invoke(
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\errors\rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ButtonDataInvalid: Telegram says: [400 BUTTON_DATA_INVALID] - The button callback data is invalid or too large (caused by "messages.EditMessage")
[10-May-24 07:57:00 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 07:57:00 - INFO] - bot - Bot stopped.
[10-May-24 07:57:08 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 07:57:08 - INFO] - bot - Lets roll
[10-May-24 08:08:55 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 08:08:55 - INFO] - bot - Bot stopped.
[10-May-24 08:09:03 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 08:09:03 - INFO] - bot - Lets roll
[10-May-24 08:09:17 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 08:09:17 - INFO] - bot - Bot stopped.
[10-May-24 08:09:25 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 08:09:25 - INFO] - bot - Lets roll
[10-May-24 08:14:39 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 08:14:39 - INFO] - bot - Bot stopped.
[10-May-24 08:14:48 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 08:14:48 - INFO] - bot - Lets roll
[10-May-24 08:17:04 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 08:17:04 - INFO] - bot - Bot stopped.
[10-May-24 08:17:13 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 08:17:13 - INFO] - bot - Lets roll
[10-May-24 08:18:47 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 08:18:47 - INFO] - bot - Bot stopped.
[10-May-24 08:18:56 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 08:18:56 - INFO] - bot - Lets roll
[10-May-24 08:35:28 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 08:35:28 - INFO] - bot - Bot stopped.
[10-May-24 08:35:38 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 08:35:38 - INFO] - bot - Lets roll
[10-May-24 08:36:06 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 08:36:06 - INFO] - bot - Bot stopped.
[10-May-24 08:36:15 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 08:36:15 - INFO] - bot - Lets roll
[10-May-24 08:36:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 08:36:40 - INFO] - bot - Bot stopped.
[10-May-24 08:36:48 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 08:36:48 - INFO] - bot - Lets roll
[10-May-24 08:37:04 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 08:37:04 - INFO] - bot - Bot stopped.
[10-May-24 08:37:12 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 08:37:12 - INFO] - bot - Lets roll
[10-May-24 08:40:58 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 08:40:58 - INFO] - bot - Bot stopped.
[10-May-24 08:41:05 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 08:41:05 - INFO] - bot - Lets roll
[10-May-24 08:41:36 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 08:41:36 - INFO] - bot - Bot stopped.
[10-May-24 08:41:45 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 08:41:45 - INFO] - bot - Lets roll
[10-May-24 08:43:41 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 08:43:41 - INFO] - bot - Bot stopped.
[10-May-24 08:43:50 - ERROR] - pyrogram.dispatcher - 'Bot' object has no attribute 'username'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\on_message.py", line 53, in handle_message
    isSuccess, cloudLink, share_link, post_message = await moveto_cloud(client, message)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\link_generator.py", line 81, in moveto_cloud
    link = f"https://t.me/{client.username}?start={base64_string}"
                           ^^^^^^^^^^^^^^^
AttributeError: 'Bot' object has no attribute 'username'
[10-May-24 08:43:50 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 08:43:50 - INFO] - bot - Lets roll
[10-May-24 08:49:06 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 08:49:06 - INFO] - bot - Bot stopped.
[10-May-24 08:49:16 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 08:49:16 - INFO] - bot - Lets roll
[10-May-24 08:53:26 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 08:53:26 - INFO] - bot - Bot stopped.
[10-May-24 08:53:34 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 08:53:34 - INFO] - bot - Lets roll
[10-May-24 09:06:00 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 09:06:00 - INFO] - bot - Bot stopped.
[10-May-24 09:07:38 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 09:07:38 - INFO] - bot - Lets roll
[10-May-24 09:09:48 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 09:09:48 - INFO] - bot - Bot stopped.
[10-May-24 09:09:56 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 09:09:56 - INFO] - bot - Lets roll
[10-May-24 09:13:17 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 09:13:17 - INFO] - bot - Bot stopped.
[10-May-24 09:13:26 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 09:13:26 - INFO] - bot - Lets roll
[10-May-24 09:20:13 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 09:20:13 - INFO] - bot - Bot stopped.
[10-May-24 09:21:13 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 09:21:13 - INFO] - bot - Lets roll
[10-May-24 09:23:11 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 09:23:11 - INFO] - bot - Bot stopped.
[10-May-24 09:23:19 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 09:23:19 - INFO] - bot - Lets roll
[10-May-24 09:23:23 - ERROR] - pyrogram.dispatcher - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\middlewares\__init__.py", line 17, in ensure_user_issubscribed_channel
    await not_joined(client, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\start_command.py", line 126, in not_joined
    url=f"https://t.me/{client.username}?start={message.command[1]}",
                                                ~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
[10-May-24 09:25:38 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 09:25:38 - INFO] - bot - Bot stopped.
[10-May-24 09:25:47 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 09:25:47 - INFO] - bot - Lets roll
[10-May-24 09:25:53 - ERROR] - pyrogram.dispatcher - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\middlewares\__init__.py", line 17, in ensure_user_issubscribed_channel
    await not_joined(client, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\start_command.py", line 126, in not_joined
    url=f"https://t.me/{client.username}?start={message.command[1] if not None else ''}",
                                                ~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
[10-May-24 09:26:10 - ERROR] - pyrogram.dispatcher - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\middlewares\__init__.py", line 17, in ensure_user_issubscribed_channel
    await not_joined(client, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\start_command.py", line 126, in not_joined
    url=f"https://t.me/{client.username}?start={message.command[1] if not None else ''}",
                                                ~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
[10-May-24 09:26:15 - ERROR] - pyrogram.dispatcher - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\middlewares\__init__.py", line 17, in ensure_user_issubscribed_channel
    await not_joined(client, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\start_command.py", line 126, in not_joined
    url=f"https://t.me/{client.username}?start={message.command[1] if not None else ''}",
                                                ~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
[10-May-24 09:26:15 - ERROR] - pyrogram.dispatcher - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\middlewares\__init__.py", line 17, in ensure_user_issubscribed_channel
    await not_joined(client, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\start_command.py", line 126, in not_joined
    url=f"https://t.me/{client.username}?start={message.command[1] if not None else ''}",
                                                ~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
[10-May-24 09:26:23 - ERROR] - pyrogram.dispatcher - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\middlewares\__init__.py", line 17, in ensure_user_issubscribed_channel
    await not_joined(client, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\start_command.py", line 126, in not_joined
    url=f"https://t.me/{client.username}?start={message.command[1] if not None else ''}",
                                                ~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
[10-May-24 09:26:41 - ERROR] - pyrogram.dispatcher - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\middlewares\__init__.py", line 17, in ensure_user_issubscribed_channel
    await not_joined(client, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\start_command.py", line 126, in not_joined
    url=f"https://t.me/{client.username}?start={message.command[1] if not None else ''}",
                                                ~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
[10-May-24 09:26:44 - ERROR] - pyrogram.dispatcher - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\middlewares\__init__.py", line 17, in ensure_user_issubscribed_channel
    await not_joined(client, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\start_command.py", line 126, in not_joined
    url=f"https://t.me/{client.username}?start={message.command[1] if not None else ''}",
                                                ~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
[10-May-24 09:26:46 - ERROR] - pyrogram.dispatcher - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\middlewares\__init__.py", line 17, in ensure_user_issubscribed_channel
    await not_joined(client, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\start_command.py", line 126, in not_joined
    url=f"https://t.me/{client.username}?start={message.command[1] if not None else ''}",
                                                ~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
[10-May-24 09:26:49 - ERROR] - pyrogram.dispatcher - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\middlewares\__init__.py", line 17, in ensure_user_issubscribed_channel
    await not_joined(client, message)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\start_command.py", line 126, in not_joined
    url=f"https://t.me/{client.username}?start={message.command[1] if not None else ''}",
                                                ~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
[10-May-24 09:28:06 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 09:28:06 - INFO] - bot - Bot stopped.
[10-May-24 09:29:01 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 09:29:01 - INFO] - bot - Lets roll
[10-May-24 09:31:04 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 09:31:04 - INFO] - bot - Bot stopped.
[10-May-24 09:31:13 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 09:31:13 - INFO] - bot - Lets roll
[10-May-24 09:32:24 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 09:32:24 - INFO] - bot - Bot stopped.
[10-May-24 09:32:32 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 09:32:32 - INFO] - bot - Lets roll
[10-May-24 09:33:44 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 09:33:44 - INFO] - bot - Bot stopped.
[10-May-24 09:33:56 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 09:33:56 - INFO] - bot - Lets roll
[10-May-24 09:35:23 - INFO] - root - Stop signal received (SIGINT). Exiting...
[10-May-24 09:35:23 - INFO] - bot - Bot stopped.
[10-May-24 09:35:33 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[10-May-24 09:35:33 - INFO] - bot - Lets roll
